service:
  type: LoadBalancer
  port: 80
replicaCount: 2
storage:
  size: 1Gi
image:
  repository: weatherappregistry2026.azurecr.io/weather-api
  tag: "1ceaf32fa007f09a16b802614c85c8551a4cb172-broken"

tag: "1ceaf32fa007f09a16b802614c85c8551a4cb172"