service:
  type: LoadBalancer
  port: 80
replicaCount: 2
storage:
  size: 1Gi
image:
  repository: weatherappregistry2026.azurecr.io/weather-api
  tag: "624e10361801973673f5a133127f56403600d96e"

tag: "624e10361801973673f5a133127f56403600d96e"