service:
  type: LoadBalancer
  port: 80
replicaCount: 2
storage:
  size: 1Gi
image:
  repository: weatherappregistry2026.azurecr.io/weather-api
<<<<<<< HEAD
  tag: "7b115ddce99f003e7eeec6e8a9b1a3445fd2b673"
=======
  tag: "7b115ddce99f003e7eeec6e8a9b1a3445fd2b673"
>>>>>>> 4630a14596c12076c5a2f531ac5471ad5ac06c59

tag: "7b115ddce99f003e7eeec6e8a9b1a3445fd2b673"