service:
  type: LoadBalancer
  port: 80
replicaCount: 2
storage:
  size: 1Gi
image:
  repository: weatherappregistry2026.azurecr.io/weather-api
<<<<<<< HEAD
  tag: "1ceaf32fa007f09a16b802614c85c8551a4cb172-broken"
=======
  tag: "624e10361801973673f5a133127f56403600d96e"
>>>>>>> 4630a14596c12076c5a2f531ac5471ad5ac06c59

tag: "624e10361801973673f5a133127f56403600d96e"