name: Build and Push to ACR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/weather-api:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/weather-api:${{ github.sha }}
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AZURE_RG }}
          cluster-name: ${{ secrets.AZURE_AKS_NAME }}

#Commenting below Helm deploy for implementing ArgoCd
#      - name: Helm Deploy
#        run: |
#          kubectl create namespace dev-environment --dry-run=client -o yaml | kubectl apply -f -
#          helm upgrade --install weather-api ./weather-app \
#            --namespace dev-environment \
#            --set image.repository=${{ secrets.ACR_LOGIN_SERVER }}/weather-api \
#            --set image.tag=${{ github.sha }} \
#            --debug
      - name: Update Image Tag in values.yaml
        run: |
        # Using 'sed' to find the tag line and replace the value
          sed -i "s/tag: .*/tag: \"${{ github.sha }}\"/" ./weather-app/values.yaml
        
        # Configure Git
          git config --global user.name "Anuj Github Action bot"
          git config --global user.email "anujpal4448@gmail.com"

          git add ./weather-app/values.yaml
          git commit -m "chore: update image tag to ${{ github.sha }} [skip ci]"
          git push
